### ISSUE TITLE
Use cog files

### ISSUE THREAD

**Issue by wakfi** [Synergile/Synergile#21]
We should use files for each command ("cogs") and seperate them into folders

**Comment by SSwiftGamer440** [comment]
Lmao I know what cogs are

**Comment by wakfi** [comment]
That's great I'm sure all of us do, this isn't directed at anyone specifically though and skipping defining things because we we think everyone is on the same page already doesn't lead to good code

**Comment by wakfi** [comment]
This [gist](https://gist.github.com/leovoel/46cd89ed6a8f41fd09c5) has a good example of what appears to be modern cog usage; last updated 2 months ago.

**Comment by wakfi** [comment]
I am uncertain of that gist. It has some accurate stuff and some I'm not sure stuff. Here's the [official documentation](https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html) of cogs
