### ISSUE TITLE
Rich presence

### ISSUE THREAD

**Issue by wakfi** [Synergile/Synergile#22]
The rich presence should say something

**Comment by SSwiftGamer440** [comment]
Will work on this

**Comment by wakfi** [comment]
The is already linked to a pull request. I didn't assign Napkins to this because you haven't added them as a collaborator yet so I can't

**Comment by wakfi** [comment]
@NapkinsXYZ can you make another branch and pull request for this? It doesn't look like the change in #19 stuck, not sure why

**Comment by NapkinsXYZ** [comment]
Alrighty, will do so later today

**Comment by wakfi** [comment]
Scratch that, I see now it is merged into my my branch. This should be fine then. I'll link it when I open my pull request
