### ISSUE TITLE
LICENSE currently refers to no one

### ISSUE THREAD

**Issue by wakfi** [Synergile/Synergile#40]
https://github.com/Synergile/Synergile/blob/13cded3531007a7680972d20937c7ba6e801cf90/LICENSE#L3

The project is currently licensed under CodeWritten's old username, meaning it isn't licensed to any of us currently. Under the terms of the MIT License we are able to update it. My suggestion is that we update the copyright holder to be the Synergile organization.

**Comment by NapkinsXYZ** [comment]
I agree

**Comment by wakfi** [comment]
I'm gonna backtrack a little bit, due to how legal enforcement work. In order for the license to have the proper legal effect, and in this case the legal effect is that people other than us are allowed to use any portion of our software and we are not liable for uses of our software by people other than us, we need to have some [legally](https://softwareengineering.stackexchange.com/a/154782) [binding](https://softwareengineering.stackexchange.com/questions/118835/can-i-use-my-username-in-a-legal-license) [names](https://softwareengineering.stackexchange.com/a/279761). We may want to consider incorporating the Synergile name (I think one of those suggested something along those lines), or listing our proper names in the license. I normally license my own projects under my real name because of all this, for context.

**Comment by DaRealCodeWritten** [comment]
If adding our names is what it takes, then alrighty! @wakfi @NapkinsXYZ @jedi3r4, in the order I pinged you guys please commit the appropriate changes to LICENSE.md to add your proper names to said file. this issue is to remain OPEN until the changes have been made. I will go first
